config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "flats#index"
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord

  validates :name, presence: true
  validates :address, presence: true
  validates :description, presence: true, length: { minimum: 100 }
  validates :price_per_night, presence: true
  validates :number_of_guests, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController

  before_action :set_flat, except: %w[index new create]

  def index
    if params['query']
      @flats = Flat.where('name LIKE ?', "%#{params[:query]}%").or(Flat.where('address LIKE ?', "%#{params[:query]}%"))
    else
      @flats = Flat.all
    end
  end

  def show; end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new
    end
  end

  def edit; end

  def update
    @flat.update(flat_params)

    redirect_to flat_path(@flat)
  end

  def destroy
    @flat.destroy

    redirect_to root_path
  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for @flat do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <div class="row">
    <div class="col-6">
      <%= f.input :price_per_night %>
    </div>
    <div class="col-6">
      <%= f.input :number_of_guests %>
    </div>
  </div>
  <%= f.submit "Add a new flat", class: "btn btn-dark" %>
<% end %>

app/views/flats/edit.html.erb
<%= render "form", flat: @flat %>

app/views/flats/index.html.erb
<div class="row">
<% @flats.each do |flat| %>
  <div class="col-3">
    <div class="card" style="height: 400px;">
      <img src="https://images.unsplash.com/photo-1464890100898-a385f744067f?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=80&raw_url=true&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470" class="card-img-top" alt="">
      <div class="card-body d-flex flex-column">
        <h5 class="card-title"><%= flat.name %></h5>
        <p class="card-text"><%= flat.description.first(45) + "..." %></p>
        <%= link_to "See more", flat_path(flat), class: "btn btn-dark align-bottom" %>
      </div>
    </div>
  </div>
<% end %>

</div>

app/views/flats/new.html.erb
<%= render "form", flat: @flat %>

app/views/flats/show.html.erb
<%= @flat.name %>
<%= @flat.address %>
<%= @flat.description %>

<%= link_to "Home", root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar fixed-top navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand ms-3 flex-grow-1" href="/">
          <img src="https://thebusinessjournal.com/wp-content/uploads/2019/05/1280px-Airbnb_Logo_Be%CC%81lo.svg_.png" alt="" width="100" height="32">
        </a>
        <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="query">
          <button class="btn btn-dark btn-rounded" type="submit">Search</button>
        </form>
        <%= link_to "Add a new flat", new_flat_path, class: "ms-3 btn btn-outline-dark btn-rounded"%>
      </div>
    </nav>

    <div class="container" style="padding-top: 80px;">
      <%= yield %>
    </div>
  </body>
</html>